version: '2'
services:
  database:
    image: mysql:5.7
    container_name: keiron-db
    volumes:
      - ./mysql/data/db:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    restart: always
    ports:
      - 3306:3306
    environment:
      DB_DATABASE: keirondb
      DB_USERNAME: keiron
      DB_PASSWORD: rootpw
    networks:
      - app-network
  server:
    image: nginx:latest
    container_name: keiron-server
    ports:
      - 80:80
    volumes:
      - ./api:/usr/share/nginx/html
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    volumes_from:
      - api
    networks:
      - app-network
  api:
    build: ./api
    container_name: keiron-api
    volumes:
      - ./api:/usr/share/nginx/html
      - /usr/share/nginx/html/vendor
    networks:
      - app-network
    links:
      - database:keiron-db
  client:
    build: ./client
    container_name: keiron-client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
networks:
  app-network:
    driver: bridge

